worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name 84.201.172.216;  # Указываем внешний IP-адрес

        location / {
            proxy_pass http://web:8000;  # Проксируем запросы к вашему Django-приложению
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /app/static/;  # Путь к статическим файлам
        }

        location /media/ {
            alias /app/media/;  # Путь к медиафайлам
        }
    }
}
