user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name 84.201.172.216;  # Замените на ваш домен или IP-адрес

        location / {
            proxy_pass http://127.0.0.1:8000;  # Прокси на Django, работающий на порту 8000
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /path/to/your/static/directory;  # Путь до директории static
        }

        location /media/ {
            alias /path/to/your/media/directory;  # Путь до директории media
        }

        # Для обработки ошибок
        error_page 500 502 503 504 /500.html;
        location = /500.html {
            root /usr/share/nginx/html;
        }

        # Настройки для безопасности
        client_max_body_size 100M;
        gzip on;
        gzip_types text/css application/javascript application/json;
    }
}
