# Generated by Django 5.1.4 on 2025-01-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(
                verbose_name="Время на выполнение (в секундах)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Периодичность (в днях)"
            ),
        ),
    ]
